name: rockie
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  api_service:
    git:
      url: https://github.com/hamidjalili59/api_service.git
      ref: main
  database_service:
    git:
      url: https://github.com/hamidjalili59/database_service.git
      ref: main
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  toastification: ^2.1.0
  riverpod_annotation: ^2.3.5
  json_annotation: ^4.9.0
  hooks_riverpod: ^2.5.1
  go_router: ^14.2.3
  freezed_annotation: ^2.4.4
  fpdart: ^1.1.0
  flutter_svg: ^2.0.10+1
  dio: ^5.5.0+1
  logger: ^2.4.0
  hive_flutter: ^1.1.0
  shimmer: ^3.0.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0
  freezed: ^2.5.7
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0

flutter_gen:
  output: lib/src/core/gen/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
